### ISSUE TITLE
Does not compile in eclipse

### ISSUE THREAD

**Issue by dobesv** [functionaljava/functionaljava#113]
It seems like functionaljava is a great test case for the Java 8 compiler.  I filed a bug with eclipse, and I thought I would put a link to there from here in case someone else runs into the same issues, basically marking this as a known issue with functionaljava in eclipse.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=461004

Note that if you are just using the functionaljava jar files this is not an issue.

**Comment by mperry** [comment]
Thanks for reporting this for others.  I am going to close this as an open issue for this project.
