### ISSUE TITLE
Provide equals/hashCode/toString for fj.List<A>

### ISSUE THREAD

**Issue by samreid** [functionaljava/functionaljava#14]
fj.List should provide a default implementation of equals, hashCode and toString that uses the .equals(), .hashCode() and .toString() implementations of its members. For instance, this equality check on the same list contents currently fails:

    public class TestList { 
        public static void main( String[] args ) { 
            final java.util.List<Integer> myList = Arrays.asList( 1, 2, 3 ); 
            boolean equal = iterableList( myList ).equals( iterableList( myList ) ); 
            System.out.println( "equal = " + equal );//prints false 
        } 
    } `

Discussion of this topic was provided here:
https://groups.google.com/forum/?fromgroups#!topic/functionaljava/qc5fUHOg0AU

**Comment by mperry** [comment]
Looks like PR #15 solved this issue.  I created #75 to remind us we can do this for various other clases.  Closing this issue unless anyone has any objections.
