### ISSUE TITLE
Consider naming convention and location for optic instances for #132

### ISSUE THREAD

**Issue by mperry** [functionaljava/functionaljava#154]

**Comment by orionll** [comment]
What if we put optic instances into static nested classes of corresponding classes? E.g. List.Optic.*, P1.Optic.*

**Comment by mperry** [comment]
I have had a think about this @orionll and have come around to your suggestion.  I think I will do this.

**Comment by jbgi** [comment]
:+1:

**Comment by jbgi** [comment]
@mperry then you can remove the extraneous Lens suffix of P2 lenses.

**Comment by orionll** [comment]
@jbgi _1() instead of _1Lens()?

**Comment by orionll** [comment]
Also, we should think where to put optic instances for standard Java classes.

**Comment by jbgi** [comment]
@mperry yes.
@orionll It makes sense to have Iso instances, eg. between java.util.Optional and Option, between java.util.Supplier and P1, and maybe for java.util.List <-> fj.data.List (with the canvas that java.util.List is mutable).
but not sure what instances are you suggesting for Boolean and Integer?

**Comment by orionll** [comment]
@jbgi https://github.com/julien-truffaut/Monocle/blob/master/core/src/main/scala/monocle/std/Int.scala

**Comment by mperry** [comment]
There will still need to be an indiciator of whether it is using the polymorphic or monomorphic class version, e.g. `P2.Optic._1p()`.

**Comment by jbgi** [comment]
@mperry true.
@orionll yes right, we should probably do a port of all relevant optics from monocle.

**Comment by orionll** [comment]
@jbgi We can put them into fj.data.Java class
