### ISSUE TITLE
Implement Validation.sequence

### ISSUE THREAD

**Issue by mperry** [functionaljava/functionaljava#163]
Related to #162 

See @tonymorris code at https://gist.github.com/tonymorris/cbc051406b974df69e69

**Comment by mperry** [comment]
Hi @tsechov, are you going to create a PR for this issue?

**Comment by tsechov** [comment]
hi @mperry,
that's the plan, yes. early next week I guess.
if thats too late, feel free to fix it.

**Comment by mperry** [comment]
@tsechov I have implemented this to get it into the code repository.
