### ISSUE TITLE
Error: sequenceWhile() cannot be accesed from outside package

### ISSUE THREAD

**Issue by Idrek** [functionaljava/functionaljava#164]
Definition of `sequenceWhile()` function is:
```
static <A> IO<Stream<A>> sequenceWhile(final Stream<IO<A>> stream, final F<A, Boolean> f) { ... }
```

And the code:

```python
Stream<IO<String>> s = Stream.repeat(stdinReadLine());
IO<Stream<String>> io = IOFunctions.sequenceWhile(s, s2 -> s2.length() > 1);
```

gives me an error **Cannot be accesed from outside package**

Now I realised that must be a problem of the Gradle import or something, because the code in Github is fine, so I will close it.

**Comment by mperry** [comment]
@Idrek I checked the visibility on those functions and they are `public static`, so I will expect it is ok.  Let us know if you continue to have a problem.

**Comment by mperry** [comment]
@Idrek I import the Gradle build.gradle file using Intellij 14.1 Community Edition.  I don't know if this helps you though.

**Comment by Idrek** [comment]
Hello @mperry ,
I continue with the problem, I'm using same Intellij version that yours in Ultimate Edition, and either importing 4.2 version like:
```
compile "org.functionaljava:functionaljava:4.2"
compile "org.functionaljava:functionaljava-java8:4.2"
```
or
4.3 like:
```
compile "org.functionaljava:functionaljava:4.3"
compile "org.functionaljava:functionaljava-java8:4.3"
```
I find same problem. I've checked the source code in Intellij Idea (External libraries) and `sequenceWhile()` doesn't appear as `public`, so I suppose Maven's version is a little bit older than the source code of Github or in any way is not well synchronized, but that's only my supposition, not sure about it.

**Comment by mperry** [comment]
@Idrek I know the issue.  In IOFunctions, `sequenceWhile` was just a `static` method in 4.3.  In 4.4-SNAPSHOT is has change to be a `public static` method.  You will have to use the 4.4-SNAPSHOT or put it into the same package.  Given new IOFunctions were added recently, I suggest you use the 4.4-SNAPSHOT version for trying things out.  I hope to release 4.4 in the next couple of weeks.

**Comment by Idrek** [comment]
All clear now. Thank you very much, @mperry
