### ISSUE TITLE
Stream.toList is inefficient

### ISSUE THREAD

**Issue by mperry** [functionaljava/functionaljava#180]
Current version for Stream.toList has time complexity O(n^2), rather than O(n).  It should use internal mutable buffer List.Buffer.

See https://groups.google.com/forum/#!topic/functionaljava/0hkgfQEXtoE

**Comment by mperry** [comment]
Thanks for raising this @clinuxrulz.

**Comment by ms-tg** [comment]
May I suggest adding performance regression tests for these sorts of fixes? Either via one of the micro-benchmark libraries where you do something like `assertLinear(...)`, or by passing in a side-effecting function into calculations which records number of operations?

**Comment by mperry** [comment]
Do you have a library in mind @ms-tg?

**Comment by ms-tg** [comment]
@mperry I think using [jmh](http://java-performance.info/jmh/) for the micro-benchmark infrastructure, but may have to create our own tooling here to structure the tests around the jmh results...

**Comment by mperry** [comment]
I'm not familiar with the libraries for micro benchmarking code.  I'd have to have a look around, but I agree it should be done.

Perhaps you'd like to submit a PR for this test to get us started with the library and act as an example.

**Comment by ms-tg** [comment]
Ha, I'll see if I have time ;) Cheers.
