### ISSUE TITLE
Full Java8 branch?

### ISSUE THREAD

**Issue by jbgi** [functionaljava/functionaljava#184]
I believe that in a near future most projects will use java 8 or later version.
I think it will be beneficial for fj adoption to start working on a new version of the library that take better advantage of the new java8 features and (maybe) offer better compatibility with the jdk.

eg. `Semigroup` could then be a `@FunctionalInterface` with default methods and (maybe) could inherit from `j.u.f.BinaryOperator` .

WDYT?

**Comment by mperry** [comment]
I generally agree.  Java 8 was available April 2014 and Java 7 reached end of life in April 2015.

I don't think it is necessary to backport features for the new version, but this might be possible.  Depending on how far we go, we might be able to backport most of it using retolambda (see https://github.com/orfjackal/retrolambda) including lambdas, method references, try-with-resources, default methods and static interface methods.  In this case, I see the project publishing  2 different types of artifacts (for Java 7 and 8).

**Comment by jbgi** [comment]
ok. as a first step I will try to sketch a port of algebra 'typeclasses' to java 8 in my repo.

**Comment by mperry** [comment]
Sounds good.  I'd say this would be a version 5.0 release.

**Comment by tonymorris** [comment]
I agree. I wonder if it is worth constructing a strategy so as to fully utilise java8 as well as still be available to java7. What is the penalty for different strategies?

**Comment by jbgi** [comment]
The main limitation is https://github.com/orfjackal/retrolambda#known-limitations
That is if we use default methods in, say, ```Semigroup```,  jdk7 implementations of the interface in client code will need to implement them anyway, although the implementations should be able to delegate to static methods generated by retrolambda in ```Semigroup$```

**Comment by jbgi** [comment]
I've done some experiments encoding 'type-classes' (Semigroup/Monoid) with interfaces (Monoid inheriting from Semigroup) and default methods. And I can't say I'm happy with the result, I like the current design (no-inheritance and a conversion method from Monoid to Semigroup) better. With some minor improvements it should be totally fine. I will try to describe the main pain points of using interfaces later on. Anyway I think defaults methods are not worth a breaking change at all.

**Comment by ms-tg** [comment]
@jbgi Is there a quick wiki page or document with an overview explaining how type-classes are currently encoded in FJ? If not, perhaps I might be able help someone knowledgable to put one together?

**Comment by jbgi** [comment]
@ms-tg not that I know of. It would certainly be valuable, with a description of the type class hierarchy:
```Ord->Equal```, ```Monoid->Semigroup```... (not obvious since not encoded via inheritance).

**Comment by jbgi** [comment]
ok. While not perfect I finally think that using interface with default methods for typeclasses are worth it and a substantial improvement when one need to override default implementation of derived methods.
An instance of this encoding here:
* Semigroup: https://bitbucket.org/jbgi/fugue/src/42eee93690f6ed6623befd87b73b921df0b344c4/fugue/src/main/java/com/atlassian/fugue/Semigroup.java?at=semigroup
* Semigroup instances: https://bitbucket.org/jbgi/fugue/src/42eee93690f6ed6623befd87b73b921df0b344c4/fugue/src/main/java/com/atlassian/fugue/Semigroups.java?at=semigroup
* Monoid: https://bitbucket.org/jbgi/fugue/src/42eee93690f6ed6623befd87b73b921df0b344c4/fugue/src/main/java/com/atlassian/fugue/Monoid.java?at=semigroup
* Monoid instances: https://bitbucket.org/jbgi/fugue/src/42eee93690f6ed6623befd87b73b921df0b344c4/fugue/src/main/java/com/atlassian/fugue/Monoids.java?at=semigroup

@functionaljava: WDYT?

**Comment by tonymorris** [comment]
+1

The hard part is achieving maximum benefit for older versions
simultaneously. Certainly doable.

**Comment by gliptak** [comment]
https://github.com/functionaljava/functionaljava/pull/359

**Comment by mperry** [comment]
Closing this issue.  Given how much time has passed, we should release a version targeting JVM 8 and 11, which I suggest would be FJ 5 and 6 respectively.  I'm going to try to get a FJ 5 released in the next 2 weeks.  FYI, Java 17 is released Sep 2021.

**Comment by tonymorris** [comment]
Nice, lmk if I can help.
