### ISSUE TITLE
Add Void: a logically uninhabited data type

### ISSUE THREAD

**Issue by jbgi** [functionaljava/functionaljava#193]
from https://hackage.haskell.org/package/void-0.7.1/docs/Data-Void.html

with Void you can implements technics like http://www.haskellforall.com/2015/01/total-100-exhaustive-pattern-matching.html

The implementation would be something like:
```java
public abstract class Void {
    private Void() {throw new IllegalStateException("Void cannot be instantiated"); }
    public abstract <X> X absurd();
}
```

WDYT ?

**Comment by mperry** [comment]
We should have this.  I think I first came across this in Harper's type theory book.  Would you like to submit a PR?

**Comment by jbgi** [comment]
yes. will do.

**Comment by mperry** [comment]
I am going to wrap things up with doc in the next week so we do a release before Christmas.

**Comment by jbgi** [comment]
666th commit: Void is coming! Beware FP non-believers! ok... ~~> :door:
