### ISSUE TITLE
Overloaded static List.list is too ambiguous

### ISSUE THREAD

**Issue by mrbackend** [functionaljava/functionaljava#194]
```List.list(1)``` equals ```List.single(1)``` but ```List.list(List.nil())``` does not equal ```List.single(List.nil())```.

This because overloading resolution prefers ```List.list(Iterable<A> i)``` over ```List.list(A... as)```.

This is easily avoided by consistently using ```List.single``` when applicable, but the ambiguity is a source of hard to discover bugs.

Might I suggest deprecating ```List.list(Iterable<A> i)``` and introduce another method, e.g. ```List.fromIterable(Iterable<A> i)```? The same ambiguity applies to ```List.list(Iterator<A> it)```, though the use case of a list of a single iterator seems much less likely than a list of a single list. I'd still suggest changing the name of ```List.list(Iterator<A> it)``` the same way.

**Comment by jbgi** [comment]
:+1:

**Comment by mrbackend** [comment]
BTW, I realize that the result types of the two expressions are different, but Java does not always support type safety, like when using varargs. I discovered this issue when creating an expression like ```List.list(List.list(List.list(1),List.list(2)),List.list(List.list(1,2)))``` (i.e. a list of possible ways to partition ```[1, 2]```. The result was ```[[[1], [2]], [1, 2]]```, not ```[[[1], [2]], [[1, 2]]]```.

**Comment by mrbackend** [comment]
I'm a little embarrassed that I missed that my "fromIterable" is already implemented as  ```List.iterableList(Iterable<A> i)```. So, please disregard that particular suggestion. The problem with the ambiguous ```List.list``` is still remains, though.

**Comment by mperry** [comment]
It is still ambiguous and needs to change.

**Comment by mperry** [comment]
I addressed the overloading in d3e99ced4ec5f3ae4c4066a02a50da55ffc981b2 and marked the extra methods as deprecated.  They should be removed the version after next.

**Comment by mperry** [comment]
I changed Stream to be consistent with List in 64fdac726d65c9dc1f6bd38a2537f16fa65e9e95.

**Comment by mperry** [comment]
Also addressed in #230
