### ISSUE TITLE
Puzzling behaviour of List.Buffer.toList()

### ISSUE THREAD

**Issue by hencjo** [functionaljava/functionaljava#195]
It seems List.Buffer.snoc (and friends) are meant only to be used through chained calls with a final call to toList(). However, it is possible and sometimes useful to call toList() more than once. In those cases it seem to be returning bogus:

Affects FJ 4.4.

```java
enum Uni {UNI}

@Test
public void test_List_Buffer_snoc() {
	List.Buffer<Uni> lb0 = List.Buffer.<Uni>empty();

	List.Buffer<Uni> lb1 = lb0.snoc(Uni.UNI);
	List<Uni> ls1 = lb1.toList();
	assertEquals(1, ls1.length()); //As expected, ls1.length() == 1

	List.Buffer<Uni> lb2 = lb1.snoc(Uni.UNI);
	List<Uni> ls2 = lb2.toList();

	assertEquals(1, ls1.length()); // But, ls1.length() == 3 !
	assertEquals(2, ls2.length()); // Also, ls2.length() == 0 !
}
```

**Comment by jbgi** [comment]
It has been fixed by #181. Probably worth a patch release though...
Also it would be nice to have another Buffer implementation that does not require the Cons class to be mutable (even if only "privately").

**Comment by jbgi** [comment]
Also your unit test should really be part of ListTest. Would you mind a pull request?

**Comment by hencjo** [comment]
Not at all. Allow a few days for me to get a PR done. 

Thanks for letting me know that it's already fixed. I did scan through the list of new commits but apparently not thoroughly enough to realize that #181 fixed the issue.

Thanks for your help!

**Comment by jbgi** [comment]
Just realized that @mperry already added a similar test in f68ce24a012c06afc0110e71b3bfb7b5d390184c So a PR might not be necessary.

**Comment by mperry** [comment]
Originally I had planned on doing another release before Christmas, but I'd have to check how different the code is from the 4.4 release.

**Comment by mperry** [comment]
I am going to close this issue since it is already fixed.

**Comment by hencjo** [comment]
Please do. Would there be any interest in a quickcheck property to exercise
List.Buffer?

tors 10 dec. 2015 kl. 13:28 skrev Mark Perry <notifications@github.com>:

**Comment by mperry** [comment]
Of course.  There is nothing there for Buffer at the moment, so please submit a PR.

**Comment by hencjo** [comment]
Will do. Eventually :).

Thanks for all your hard work in FJ.

tors 10 dec. 2015 kl. 14:11 skrev Mark Perry <notifications@github.com>:
