### ISSUE TITLE
Nested class Array.ImmutableProjection should be static

### ISSUE THREAD

**Issue by mrbackend** [functionaljava/functionaljava#210]
Array.ImmutableProjection is both non-static and takes a type parameter. This forces the user to write `Array<TypeName>.ImmutableProjection<TypeName>` (or `Array<?>.ImmutableProjection<TypeName>`). This nested class should be static, since it doesn't use any of Array's instance fields or methods.

**Comment by mperry** [comment]
Agreed.  Can you submit a PR?

**Comment by mrbackend** [comment]
I will :)

**Comment by mrbackend** [comment]
Note: It will break backward compatibility, though.
