### ISSUE TITLE
Add support for Pattern Matching

### ISSUE THREAD

**Issue by bruce264** [functionaljava/functionaljava#212]
Functional Java is a great library, however I'd like to be able to use Patter Matching in it like https://github.com/aol/cyclops/tree/master/cyclops-pattern-matching but with the advantage that FJ doesn't require JDK 8.

**Comment by jbgi** [comment]
Could you give an example of what you want to do and what is the problem to achieve that.

Also it looks like cyclops pattern matching rely on type casing or universal equality, which can be unsafe, inconsistent and can breaks parametricity, so it is likely that FJ would not add special support to accommodate that.

For structural pattern matching on user defined data types, you may be interested in [derive4j](https://github.com/derive4j/derive4j).

**Comment by tonymorris** [comment]
Functional Java already does this, but much better, without losing safety. e.g. `Option#option` does the pattern-matching on `Option` values by accepting a `None` case and `Some` case as arguments.

The linked `isType` function is an (unnecessarily) unsafe way of implementing sum types for Java. I would recommend against implementing unsafe code for no benefit above what already exists.

**Comment by bruce264** [comment]
@jbgi Sure, basically I'd like to be able to do something around the lines of

Stream.of(0, 1, 2, 3, 13, 14, null, -1)
        .peek(n -> out.print(format("%d -> ", n)))
        .map(Match.as(Object.class) // Match function (with apply(Object))
                .when(Objects::isNull).then("!")
                .whenIs(0).then("zero")
                .whenIsIn(1, 13, 14).then(i -> "first digit 1: " + i)
                .whenType(Double.class).then(d -> "Found a double: " + d)
                .whenApplicable((Number num) -> "number: " + num).thenApply()
                .otherwise(() -> "no match"))
        .map(MatchingTest::toString)
        .forEach(out::println);
out.flush(); // Avoid mixing sout and serr

from http://javaslang.com

I am currently starting out with Functional Programming and haven't found how to do this with FJ, I'll look at Option.

**Comment by danieldietrich** [comment]
@bruce264 one note: in Javaslang Match...apply always takes an Object. With Match.as(type) you specify the result type (in a type-safe way), in your case String. Match.as is needed to give an intersection type hint, e.g when the second _then_ clause returns a super type of the first _then_ result type.

**Comment by bruce264** [comment]
@danieldietrich Ok cool, I copied the example from http://javaslang.com but it's good to know, thanks. 

@tonymorris I've looked at the examples available for Option but haven't seen one that does pattern matching, could you please point me to one?

**Comment by danieldietrich** [comment]
@bruce264 uh, oh :)

**Comment by jbgi** [comment]
@bruce264, Tony was talking about structural pattern matching via ```Option#option```, ```List#list``` or ```Stream#stream```, not guards (the```when```/```then``` methods of your example).

There is no fluent api for creating guard patterns in FJ, however you should be able to use the ones provided by cyclops or javaslang as argument of ```fj.Stream#map``` if you want to.

**Comment by bruce264** [comment]
@jbgi that seems like a nice workaround but I am using the library in Android currently which limits my JDK to version 7 so I can't leverage other libraries apart from FJ.

**Comment by jbgi** [comment]
@bruce264 well then, guards are equivalent to old fashioned (nested) ternary expressions (e1 ? e2 : e3).

**Comment by johnmcclean-aol** [comment]
@jbgi Hey JB - (only seeing this now!) - cyclops-pattern-matching definitely does not **rely** on universal equality. At the core we use Tuples of predicates & functions, and on the front end are series of builders (there's 4 at the moment - this needs to rationalized - but given backward compatibility restraints, this takes time). There is an enormous amount of flexibility (too much for sure) in both the front end and backend about how matches are triggered.

I agree with both JB & Tony that it is orders of magnitude better, in Java, to have appropriate  type safe matching built into libraries from the start. The design centre for cyclops-pattern-matching was to be able to recursively destructure data structures over which you have no control (and weren't generated by the derive4j or the FJ commiters!).

**Comment by jbgi** [comment]
@johnmcclean-aol Hey John!
by universal equality I meant Object.equals which is used in the end by cyclops, when the user does not supply its own ```Predicate```. eg. https://github.com/aol/cyclops/blob/master/cyclops-pattern-matching/src/main/java/com/aol/cyclops/matcher/builders/ADTPredicateBuilder.java#L59

**Comment by johnmcclean-aol** [comment]
@jbgi Yep, got that :) That's why I bolded the term rely. It's totally up to the end user.

**Comment by mperry** [comment]
Looks like we are not going to support this.  I will close the issue.
