### ISSUE TITLE
fj.test.Gen.pick is broken

### ISSUE THREAD

**Issue by mrbackend** [functionaljava/functionaljava#235]
public Property pick() {
      return Property.property(Arbitrary.arbitrary(Gen.pick(2,List.range(0,10))), values -> {
        System.out.println(values);
        return Property.prop(true);
      });
    }

Prints

    List(0,1,2,3,5,6,7)
    List(0,2)
    List(0,2)
    List(1,2,3,4,5,6)
    List(0,1,3,4,5,6,7,8)
    ...

It does not pick two arbitrary elements. Am I mistaken in how this function should work?

**Comment by mrbackend** [comment]
I need this to test my Trie, so I'll fix it unless I have misunderstood what's the expected behavior.

**Comment by mrbackend** [comment]
This one actually needs two questions answered:

1. Should pick() generate combinations or permutations?
2. With or without replacement? (I.e. can a generated List contain several instance of the same element?)

**Comment by jbgi** [comment]
fixed with https://github.com/functionaljava/functionaljava/commit/5c6a4d19c5bc74c4a5838dc643c3cc63a5560371
