### ISSUE TITLE
fj.test.Rand.reseed() is broken

### ISSUE THREAD

**Issue by mrbackend** [functionaljava/functionaljava#237]
`Rand.choose(from,to)` called on the instance returned by `reseed()` returns the same value every time for the same arguments. This is not what `reseed()` should do.

This in turn breaks `Gen.variant()`, most of the methods and coarbitraries in `Coarbitrary` and potentially everything that depends on `Coarbitrary`, including several `arb...()` methods in `Arbitrary`.

The problem is not that `reseed()` is incorrectly implemented, rather that `Rand` is incorrectly designed. Its public `rand(f,g)` method enables users to plug in their own random generators, but given only the functions `f` and `g`, there is no way `Rand` can know how to reseed that externally instantiated random generator.

(It is technically possible to use the seed to create a function that transforms the output from `f`/`g` within `from`..`to`, but this could potentially make a good random generator bad - PRNG design should be left to the mathematicians - and besides, that solution would look like the band aid it would be.)

I suggest adding a new `rand(f,g,F<Long,Rand> onReseed)` method, deprecate the existing `rand(f,g)` method and make `reseed()` throw an exception when called on `Rand` instances created with the deprecated method.

Aaand - since I need this one to get working `arbF()`-instances in my property tests, I think I'll just go ahead and implement it.

**Comment by jbgi** [comment]
fixed with https://github.com/functionaljava/functionaljava/commit/498e59b11dd9a9090c3b766bff3815645bd31ba2
