### ISSUE TITLE
Hard memo, memory reduction.

### ISSUE THREAD

**Issue by clinuxrulz** [functionaljava/functionaljava#257]
For a hard memo (```P1.hardMemo()```), once the value has been calculated you can drop the reference to the computation, since the value will not be recalculated again. This allows the reference to the computation to become garbage collected.

**Edit:** By drop the reference, I mean set ```self``` to ```null```.

**Comment by jbgi** [comment]
@clinuxrulz do you want to submit a PR to fix this?

**Comment by clinuxrulz** [comment]
OK. #258

**Comment by jbgi** [comment]
Thanks! Merged with 97b767e89e6db089c5f763971c3224b302eeb5db
