### ISSUE TITLE
Captureless lambda for Equal and Ord?

### ISSUE THREAD

**Issue by clinuxrulz** [functionaljava/functionaljava#260]
I don't know if this is a big deal or not. But if you base ```Equal``` and ```Ord``` on ```F2``` rather than ```F```, then it enables you to use captureless lambdas that will avoid memory allocations when using them for comparisons.

**Comment by clinuxrulz** [comment]
Actually the common use case will be applied in curried form. I'll close this. Premature optimization.

**Comment by jbgi** [comment]
This is intended to be implemented via #284
