### ISSUE TITLE
Is there an elegant way to do if/else (pattern matching) checks with this library?

### ISSUE THREAD

**Issue by bruce264** [functionaljava/functionaljava#263]
Last time I asked this question I was bombarded with a bunch of technical jargon, let me see if I can get a yes/no answer this time, I would like to do something like this https://github.com/aol/cyclops/wiki/Pattern-Matching-Explained with functionaljava since it supports java 7 where as cyclops doesn't, is it possible?

**Comment by mperry** [comment]
Many (most perhaps?) of the classes have a method supporting pattern matching, but the library does not support this in the general sense.

```
Option.some(3).option(() -> "empty", i -> i.toString());
```

**Comment by bruce264** [comment]
So basically the answer is no, ok thanks.

**Comment by techtangents** [comment]
The answer is no. Pattern matching requires syntax which Java doesn't 
have - even in Java 7 or 8. In lieu of this, use "folds", like 
Option.option.

What you're showing in that link is not pattern matching.

**Comment by puffnfresh** [comment]
fj.data.optic.Prism does a better job of what's presented in that link.

https://github.com/functionaljava/functionaljava/blob/master/core/src/main/java/fj/data/optic/Prism.java

**Comment by bruce264** [comment]
@puffnfresh Do you have a link of how Prism can be used in practice?
