### ISSUE TITLE
Support both java 8 and java 6 binary artifacts

### ISSUE THREAD

**Issue by mperry** [functionaljava/functionaljava#265]
At the moment everything is backported to Java 6, but projects on Java 8 should be able to take advantage of runtime lambda support in Java 8.

**Comment by jbgi** [comment]
Nowadays, I think backporting to Java7 is enough. Having to install jdk6 is a burden...

**Comment by gliptak** [comment]
With https://github.com/functionaljava/functionaljava/pull/302 support for 1.8 was added.
Java6 is still targeted?
Thanks

**Comment by jbgi** [comment]
With #302 only java 7 an 8 will be target. If this is a problem we can try to set 
[`retroLambdaTarget`](https://github.com/functionaljava/functionaljava/blob/master/build.gradle#L81) to `JavaVersion.VERSION_1_6` and see if it is enough to target java 6.

**Comment by mperry** [comment]
I tried this and the build produces JVM 6 code.  That should be enough.  If we start targeting JVM 8+ with FJ 5 might be best just to continue to support 6 for 4.x versions, which means we need to change build.gradle to use 

```
retroLambdaTarget = JavaVersion.VERSION_1_6
```

**Comment by jbgi** [comment]
done in 1faf5b9184d82cca5929747f5cfb4e67100752ab
