### ISSUE TITLE
Fix all unchecked conversion warnings

### ISSUE THREAD

**Issue by mperry** [functionaljava/functionaljava#269]
Either fix or suppress these warnings.

**Comment by jbgi** [comment]
I think many of them (all ?) are due to my recent commit https://github.com/functionaljava/functionaljava/commit/5e6da6f8673ed97a2c99866662f757c2b5088e8c
I removed the ```@SuppressWarnings("unchecked")``` because the warnings are really justified as the methods are unsafe.

**Comment by mperry** [comment]
So are they all deprecated for 4.6, to be removed for 4.7?

**Comment by jbgi** [comment]
yes. we need to add this info in the comments as part of resolving #264
