### ISSUE TITLE
List.traverseValidation(x -> x) != Validation.sequence

### ISSUE THREAD

**Issue by LeifW** [functionaljava/functionaljava#287]
That traverse is implemented with bind.
Would a PR adding a Semigroup constraint be accepted?
Also, should one be implemented in terms of the other?

**Comment by jbgi** [comment]
Thanks for spotting the bug! A PR adding the semigroup is welcomed.  implementing sequence in term of traverse sounds good to me, unless there is a non negligeable performance hit.

**Comment by jbgi** [comment]
@LeifW do you have a PR in the work?
