### ISSUE TITLE
Ord.longOrd.isGreaterThan(a).f(a) yields true 

### ISSUE THREAD

**Issue by prange** [functionaljava/functionaljava#293]
The test
```java
@Test
public void longOrdIsGreaterThan() {
    Long instant1 = 1;
    Long instant2 = 2;

    F<Long, Boolean> pred = Ord.longOrd.isGreaterThan(instant1);
    assertThat(pred.f(instant2), is(true));
    assertThat(pred.f(instant1), is(false));
}
```
fails in 4.6. Ok in 4.5

**Comment by jbgi** [comment]
You mean that the first assert should fail and the second should pass, right? but it is actually the other way around.
The implementation of `isGreaterThan(A)` is actually what would be the impl. of `isGreaterThanOrEqualTo(A)`. which is, I agree is not the expected behavior.

**Comment by prange** [comment]
Sorry, typo in the original post. Fixed.
But you still figured out what i meant :)
