### ISSUE TITLE
Coveralls?

### ISSUE THREAD

**Issue by gliptak** [functionaljava/functionaljava#296]
Is Coveralls still connected? Current pull requests do not seem to generate records at:

https://coveralls.io/github/functionaljava/functionaljava

Thanks

**Comment by gliptak** [comment]
@mperry @tomjadams @tonymorris Could you check on Coveralls settings? Thanks

**Comment by tonymorris** [comment]
I am not sure who set this up. Anyone?

**Comment by gliptak** [comment]
@tonymorris Could you force an Info Sync and maybe regen the token at https://coveralls.io/github/functionaljava/functionaljava/settings ? Thanks

**Comment by tonymorris** [comment]
I have no idea what I am doing. I see this https://i.imgur.com/6B2nEek.png

and I see a token field.

**Comment by gliptak** [comment]
My fork's settings screen looks like this 
![settings](https://cloud.githubusercontent.com/assets/50109/20952541/344a3d04-bbfb-11e6-8e2b-ef31269c1f2c.png)

Do you see the word ```settings``` in the page URL (maybe you also not recognized having the right permission ...)?

**Comment by tonymorris** [comment]
I can go to Settings and I can regenerate a token. What needs doing exactly?

**Comment by gliptak** [comment]
Let's start with ```SYNC``` at the bottom of that page.
I submitted https://github.com/functionaljava/functionaljava/pull/306
I will ```--force``` it after you ran ```SYNC``` to trigger another build.

**Comment by tonymorris** [comment]
OK I pressed Sync.

**Comment by gliptak** [comment]
Sorry, not having much luck with Gradle versions.

**Comment by tonymorris** [comment]
I honestly have no idea how any of this works. Is there a button I can press to give you access?

**Comment by gliptak** [comment]
So I got a good build:

https://travis-ci.org/functionaljava/functionaljava/builds/181847121

last step of which was 
```
$ ./gradlew jacocoRootReport coveralls
```
but Coveralls didn't update.

Could you ```Regen``` the token next? 

To get the right permissions, I would need to become an ```owner``` in Github.

**Comment by gliptak** [comment]
https://github.com/lemurheavy/coveralls-public/issues/885

**Comment by gliptak** [comment]
There are also some Github outages

https://status.github.com/messages

Not helpful  :(

**Comment by tonymorris** [comment]
I added you as Owner and regenerated a token. What now?

**Comment by gliptak** [comment]
I just triggered another build

https://travis-ci.org/functionaljava/functionaljava/builds/181850241

Thank you for changing the Github permissions. Unfortunately they do not reflect on Coveralls:

https://coveralls.io/github/functionaljava/functionaljava

so I still do not see ```Settings```. Something is very borked ...

**Comment by gliptak** [comment]
Now ```Settings```  shows up.

**Comment by gliptak** [comment]
I could try removing/adding the repo in Coveralls ... WDYT?

**Comment by tonymorris** [comment]
You know better than I. I leave it to your capable hands. Let me know if I can do anything more.

**Comment by tonymorris** [comment]
I see Settings top-left.

https://i.imgur.com/zqcLPIE.png

**Comment by gliptak** [comment]
OK, I will go ahead with a recreate.

**Comment by gliptak** [comment]
Coveralls do not seem to be working, so I also submitted https://github.com/functionaljava/functionaljava/pull/308

The numbers look off some ...

https://codecov.io/gh/functionaljava/functionaljava/pull/308?src=pr

**Comment by jbgi** [comment]
@gliptak, as of the number not matching between coveralls and codecov.io: could it be that codecove.io does not take tests from props-core-scalacheck into account (because in separate module)?

**Comment by gliptak** [comment]
@jbgi The per package coverage is listed at the bottom of
https://codecov.io/gh/functionaljava/functionaljava/pull/308?src=pr
If not all of those are expected, I can add exclusions.

**Comment by andyg0808** [comment]
@gliptak FYI, that repo token isn't blacked out enough to not be readable with some tweaking of levels (or looking at an LCD monitor from the wrong angle). If you want to see for yourself, open the image in Gimp, choose the levels tool, and set the middle input level box to 2.43.

**Comment by gliptak** [comment]
@andyg0808 Thank you for noting. The Coveralls integration was removed from this project, as I couldn't make it work (so the generated key is gone, I think ...) I can edit the imgur(?) link to remove old data.

**Comment by jbgi** [comment]
Closing this as Codecov is in place and working.
