### ISSUE TITLE
add Either Projection::valueOrThrow(T extends RuntimeException)

### ISSUE THREAD

**Issue by yyaari** [functionaljava/functionaljava#315]
There are cases (for example error handling ) when an either is propagated up in the stack of method calls until it reaches a method that can handle the error.
Sometimes, instead, it would be more efficient to throw a RuntimeException from the first method that receives the erroneous either, and catch it up in the stack on the method which knows how to handle it.
Currently the only way is by using Projection::valueE(), but this method throws an Error which is fatal and should never be caught.

**Comment by jbgi** [comment]
There is `orValue` that you can use for this purpose:
```java
    e.right().orValue(() -> {throw new RuntimeException();});
    // or with a helper method:
    e.right().orValue(willThrowException(RuntimeException::new));

  static <A, E extends RuntimeException> F0<A> willThrowException(F0<E> exception) {
    return () -> {throw exception.f();};
  }
```

**Comment by yyaari** [comment]
Thanks For your reply.
Indeed this will work for me. Thanks!
