### ISSUE TITLE
Bug in Either.LeftProjection.traverseIO

### ISSUE THREAD

**Issue by sidneyquitorio8** [functionaljava/functionaljava#334]
There appears to be an issue with `Either.LeftProjection.traverseIO`. Current implementation is:

```
      public <C> IO<Either<C, B>> traverseIO(final F<A, IO<C>> f) {
          return e.isRight() ?
                  IOFunctions.map(f.f(value()), Either::<C, B>left) :
                  IOFunctions.unit(Either.right(e.right().value()));
      }
```

The issue appears to be in the conditional. Instead of checking if its a left & applying the function, it checks if its a right. Doing the following appears to fix this.

```
      public <C> IO<Either<C, B>> traverseIO(final F<A, IO<C>> f) {
          return e.isLeft() ?
                  IOFunctions.map(f.f(value()), Either::<C, B>left) :
                  IOFunctions.unit(Either.right(e.right().value()));
      }
```

**Comment by jbgi** [comment]
indeed! thanks for spotting the issue.
Do you want to submit a PR?

**Comment by sidneyquitorio8** [comment]
@jbgi np. heres a PR https://github.com/functionaljava/functionaljava/pull/335
