### ISSUE TITLE
Add current JDK to Travis build (allowed failure?)

### ISSUE THREAD

**Issue by gliptak** [functionaljava/functionaljava#355]
https://www.deps.co/guides/travis-ci-latest-java/

**Comment by jbgi** [comment]
:+1:  I think we can run ci against the following 2 JDKs:
 - openjdk10 (or oraclejdk10?) (last stable compiler)
 - openjdk-ea (for detecting regression that could impact FJ)

(both with the `--release 8` option)

**Comment by gliptak** [comment]
@jbgi Would we like to remove JDK7 from (Travis) build first?

**Comment by gliptak** [comment]
https://github.com/functionaljava/functionaljava/pull/359

**Comment by jbgi** [comment]
fixed by ebdceaa7653780d8c896ad08687a22b934538aa5
