### ISSUE TITLE
Documentation is incorrect for Either.iif

### ISSUE THREAD

**Issue by markusa380** [functionaljava/functionaljava#379]
The documentation of `Either.iif` states:

> If the condition satisfies, return the given A in left, otherwise, return the given B in right.

When reading the code or using common sense you will find that in reality, it should be:

> If the condition satisfies, return the given B in right, otherwise, return the given A in left.

**Comment by gliptak** [comment]
Thanks for pointing this out @MarkusA380

**Comment by markusa380** [comment]
@gliptak Close?

**Comment by gliptak** [comment]
@MarkusA380 you are welcome to close with the understanding that the next website refresh will deliver this correction
