### ISSUE TITLE
operator can not be applied to + operator

### ISSUE THREAD

**Issue by FuncGuy** [functionaljava/functionaljava#384]
i'm trying out functional java all the sample examples showing compiler error for example 

        final List<Integer> a = list(1, 2, 3);
        final List<Integer> b = a.map(add.f(42)); // or equivalently:
        final List<Integer> c = **a.map(i -> i + 42);**
        listShow(intShow).println(b); // [43,44,45]

in the above "a.map(i -> i + 42)" is showing compiler error.. i'm using jdk 12...

**Comment by gliptak** [comment]
Did you add ```import fj.data.List```?

**Comment by prayagupa** [comment]
**You might want to post what exact error you get?**

Seems to work fine for me on java 12.

```java
import org.junit.Test;

import static fj.data.List.list;
import fj.data.List;
import static fj.Show.intShow;
import static fj.Show.listShow;

public class TaskSpecs {

    @Test
    public void fp() {

        final List<Integer> a = list(1, 2, 3);
        final List<Integer> b = a.map(v -> v * 100);
        final List<Integer> c = a.map(i -> i + 42);
        listShow(intShow).println(b);
    }

}
```

with gradle config, 

```groovy
plugins {
    id 'java'
}

group 'org.prayagupd.fjava'
version '1.0-SNAPSHOT'

sourceCompatibility = 12
targetCompatibility = 12

repositories {
    mavenCentral()
}

dependencies {
    compile "org.functionaljava:functionaljava:4.8"
    compile "org.functionaljava:functionaljava-java8:4.8"
    compile "org.functionaljava:functionaljava-quickcheck:4.8"
    compile "org.functionaljava:functionaljava-java-core:4.8"

    testCompile group: 'junit', name: 'junit', version: '4.12'
}

```

**Comment by gliptak** [comment]
@prayagupd thank you for checking on this

@FuncGuy please provide a reproducible fail or close this issue
