### ISSUE TITLE
.equals should not throw a NullPointerException?

### ISSUE THREAD

**Issue by drewctaylor** [functionaljava/functionaljava#385]
I've noticed that in some cases, .equals will throw a NullPointerException. Examples:

```
p(null).equals(p(1));
some(null).equals(some(1));
left(null).equals(left(1));
right(null).equals(right(1));
success(null).equals(success(1));
fail(null).equals(fail(1));

```
Will throw a NPE. However, these will (correctly?) return false:

```
p(1).equals(p(null));
some(1).equals(some(null));
left(1).equals(left(null));
right(1).equals(right(null));
success(1).equals(success(null));
fail(1).equals(fail(null));
```

Is this intentional, or is it a bug? It appears in both 4.8.1 and series/5.x.

**Comment by aryairani** [comment]
@drewctaylor Hey. :) Can you tell why they do?  Like is it calling .equals on the inner values?  Guessing maybe neither intentional nor bug but “avoid null” / “blame Java”. WDYT?

**Comment by drewctaylor** [comment]
I was wondering about "avoid null", but if that were the case then (I assume) `p(null)` (among others) would throw an exception, rather than produce a valid P1 - or at least that it wouldn't matter on which side of the `.equals` that the `p(null)` appears, it would throw an exception in both cases. Will look into getting the stacktrace to isolate the location the error appears.

**Comment by aryairani** [comment]
@drewctaylor Disclaimer: I for sure don't know what I'm talking about when it comes to the specifics of this library, but my guess is it's a softer "using null results in undefined behavior" vs "we will alert you at the first sign of nulls". So it _happens_ to work in one direction, just like how, `"Foo".equals(null)` is ok in plain Java but `null.equals("Foo")` throws an NPE.  It would be nice if they returned the same thing, but I dunno exactly what the library maintainers are going for.  

I guess one could do a special check in the `Equal` implementation for `null`s; currently there's no mention of `null` in there.

**Comment by mperry** [comment]
@aryairani has it right.  Use Option's methods none, fromNull, toNull to handle nulls.  Any other use of null is undefined behaviour, the entire code base would be much more complicated if we had to assume any particular value could be null.  Unfortunately that results in discrepancies.  The two riskiest methods most likely to be affected would be equals and toString which are overriden from Object.  This is unlikely to be fixed, we don't want to encourage use of nulls.

**Comment by tonymorris** [comment]
> @aryairani has it right. Use Option's methods none, fromNull, toNull to handle nulls. Any other use of null is undefined behaviour, the entire code base would be much more complicated if we had to assume any particular value could be null. Unfortunately that results in discrepancies. The two riskiest methods most likely to be affected would be equals and toString which are overriden from Object. This is unlikely to be fixed, we don't want to encourage use of nulls.

:+1:

Also better, assume `toString` and `equals` don't exist, except to the extent of dependency libraries (`equals` in particular, since it is broken for other reasons).
