### ISSUE TITLE
Add non-jargon documentation

### ISSUE THREAD

**Issue by mleonhard** [functionaljava/functionaljava#394]
The FJ documentation is not accessible to experienced Java programmers.  It is documented only with functional programming jargon, not with standard Java software engineering terms.

For example, I have a CS degree and 7.5 years of experience working as a software engineer at Google and Amazon.  I believe I am your target user.  These javadoc entries are inaccessible to me:
1. [`Either.joinLeft()`](http://www.functionaljava.org/javadoc/4.8.1/functionaljava/fj/data/Either.html#joinLeft-fj.data.Either-) says "Joins an either through left."  This is incomprehensible to me.
1. [`Either.either()`](http://www.functionaljava.org/javadoc/4.8.1/functionaljava/fj/data/Either.html#either-fj.F-fj.F-) says "The catamorphism for either. Folds over this either breaking into left or right."  I don't understand the term *catamorphism*.
1. [`Either.traverseListLeft()`](http://www.functionaljava.org/javadoc/4.8.1/functionaljava/fj/data/Either.html#traverseListLeft-fj.F-) says "Traversable instance of LeftProjection of Either for List."  Mostly jargon.  I partially understand the concept of a projection.  I don't know what *traversable* means.

It's great for documentation to be precise and use correct terms.  When it's an advanced tool, the documentation can also serve to *teach* the advanced topic to new users.  The FJ documentation is an opportunity to teach Java coders about functional programming.  Please consider putting more effort into making the documentation accessible to new users.

Sincerely,
Michael

**Comment by JohnMcGuinness** [comment]
I have to agree with Michael.

I think if this library had understandable documentation for the average Java developer then it has the potential to be used more widely.

Although, i suspect the target audience of this library is not the average Java developer but seasoned Haskell developers who already understand the functional programming concepts and for what ever reason must use Java.

**Comment by tonymorris** [comment]
This is for the pedagogy. https://github.com/system-f/fp-course

The terminology you refer to is widely used. The only reasonable solution is to learn what it means. Catamorphism means "down-transformation" in Greek. It relates to the algebra of a data type and can be calculated if you didn't have it there already. Join is a well-understood as the canonical name for the operation M x M -> M.

I don't think teaching "jargon" with "more documentation" is helpful.

**Comment by dobesv** [comment]
I would say if you have specific suggestions on documentation improvements, open pull requests for those cases.  Asking volunteers on an open-source project that is already somewhat short on manpower to go through their entire codebase rewriting documentation seems like a lot.

**Comment by mperry** [comment]
I agree this creates a barrier to entry for experienced programmers who aren't familiar with the terminology, but I don't find this a big issue.  There are lots of terms I don't know the details of where @tonymorris is probably the original author.  I think experienced programmers who want to use more functional programming will find the library practical, but it does take patience with the terms.  

Practically speaking, reading the types involved in the type signature gives you the information you need, e.g. for your reference to joinLeft of http://www.functionaljava.org/javadoc/4.8.1/functionaljava/fj/data/Either.html#joinLeft-fj.data.Either-, the type signature is:
`public static <A,B> Either<A,B> joinLeft(Either<Either<A,B>,B> e)`
which I read as:
if on the right then keep the current value, but change the signature to fit the return type of `Either<A, B>`, if on the left, then use that left structure to match the returned structure of `Either<A, B>`.

**Comment by tonymorris** [comment]
My opinion: there is a lot of documentation already, in types, in papers, in articles, in tutorials, which has been written over several decades.

On the other hand, if I were to say, run across a good ol' [AbstractBeanFactoryAwareAdvisingPostProcessor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/aop/framework/autoproxy/AbstractBeanFactoryAwareAdvisingPostProcessor.html), which is explained like so:

> Extension of AbstractAutoProxyCreator which implements BeanFactoryAware, adds exposure of the original target class for each proxied bean (AutoProxyUtils.ORIGINAL_TARGET_CLASS_ATTRIBUTE), and participates in an externally enforced target-class mode for any given bean (AutoProxyUtils.PRESERVE_TARGET_CLASS_ATTRIBUTE). This post-processor is therefore aligned with AbstractAutoProxyCreator.

…and find that it contains 3 methods with following types…

1. `Object -> String -> boolean`
2. `Object -> String -> ProxyFactory`
3. `BeanFactory -> void`

…then I think I would argue that I have not gained knowledge; perhaps even lost some. This is an example of anti-documentation.

I would be very cautious of falling into the trap of producing anti-documentation.

**Comment by mleonhard** [comment]
I stopped using Java and switched to Rust.  Rust has exceptionally well-written [documentation](https://www.rust-lang.org/learn).  The Rust docs are accessible to programmers of all backgrounds.  I learned so much from those docs and from using Rust over the last 10 months.  I've become a better software developer.
