### ISSUE TITLE
TreeMap#split appears broken

### ISSUE THREAD

**Issue by shajra** [functionaljava/functionaljava#4]
I wrote the following test for TreeMap#split and got some unexpected behavior:  https://gist.github.com/996438.

It appears the "lesser" and "greater" value sets are being reduced to singleton sets.  I looked at the implementation

```java
public P3<Set<V>, Option<V>, Set<V>> split(final K k) {
    final F<Set<P2<K, Option<V>>>, Set<V>> getSome = Option.<V>fromSome().o(P2.<K, Option<V>>__2())
        .mapSet(tree.ord().comap(P.<K, Option<V>>p2().f(k).<V>o(Option.<V>some_())));
    return tree.split(p(k, Option.<V>none())).map1(getSome).map3(getSome)        
        .map2(Option.<V>join().o(P2.<K, Option<V>>__2().mapOption()));
}
``` 

and I'm pretty sure the problem is in extrapolating an Ord for values (which may not be comparable at all) from the Ord provided for the keys using a comap.  What the current implementation does is map each value v to (k, some(v)), where k is the split key.  Unfortunately, the original Ord only considers the first part of the tuple, which is now the constant k for all values.  So this comapping effectively makes all values in the set equal, and thus no value inserts after the first one.

Tony on #functionaljava mentioned that TreeMap might have taken some strong implementation cues from Haskell's Data.Map.  Here's the signatures for the splits of that structure:

```haskell
split :: Ord k => k -> Map k a -> (Map k a, Map k a)
splitLookup :: Ord k => k -> Map k a -> (Map k a, Maybe a, Map k a)
```

I'm happier with this implementation, because we're not returning back sets of values, but rather submaps, so we don't have to deal with having an Ord for values at all.

If you guys are in agreement of how to resolve this, I can put together a pull request with the fix and necessary tests.

**Comment by mperry** [comment]
I've had a look at this and I think @shajra is right.  The comap over the tree's ord to create an `Ord<V>` is the problem.  If I pass the `Ord<V>` as a parameter, then the method works.  Does comapping over Ord makes sense anyway to convert an `Ord<A>` into `Ord<B>`?  That is, `Ord<B> comap(final F<B, A> f)`.  If not, then should comap be removed?  Scalaz looks like it has the same method, contramap on Order.

I also have a implementation of splitLookup that works for a simple case.  I will some test code in the next few days (hopefully).

**Comment by mperry** [comment]
@davidmoten This is fixed.  You now need to pass an Ord<V> into split.  Alternately, use the new splitLookup method.

**Comment by davidmoten** [comment]
Thanks!
