### ISSUE TITLE
Will there be a release 4.8.2 / 4.9?

### ISSUE THREAD

**Issue by drewctaylor** [functionaljava/functionaljava#416]

**Comment by tonymorris** [comment]
Do you want to do a release?

**Comment by gneuvill** [comment]
I'd be willing to make a release ; I'm just not sure what is needed on my part (credentials on sonatype ? anything else ?)...

**Comment by drewctaylor** [comment]
Same as @gneuvill - I'd be willing, but I'd need to know what to do to know whether I can.

**Comment by tonymorris** [comment]
I've added Drew on the team. Lemme know if I can help in any other way.

**Comment by drewctaylor** [comment]
Thanks - let me know what's necessary to produce a release, and I'll do it.

**Comment by drewctaylor** [comment]
I'm still happy to create a release, but I'm hesitant to simply mash the "Create a new release" link on the main page - is there anything that we'd like done other than that?

**Comment by tonymorris** [comment]
Press it. I believe in you.

**Comment by mperry** [comment]
Hi @drewctaylor, I want FJ compiled under Java 8 only and the project has been stale the last few years.  I'm going to take the commits post 4.8.1 and do a 4.9 release and then merge into a 5.0 release using only Java 8.  The 5.0 release probably won't include anything other than 4.9, I'm hoping to do this over the next week.  I'll also look at the outstanding PRs.

**Comment by mperry** [comment]
I've added more to the release process in https://github.com/functionaljava/functionaljava/blob/series/5.x/etc/release-process.txt, so I can help someone to do this in the future.
