### ISSUE TITLE
Performance: Append operation of List and Array

### ISSUE THREAD

**Issue by morris821028** [functionaljava/functionaljava#428]
Hi,

When I use immutable collection with Java Stream, performance degradation happened. I found the basic List and Array always copy the whole content in O(n) time, which n is current number of elements. Is it normal for functional programming design?

```java
package persistent.array.fully;

import java.util.Iterator;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import fj.Function;
import fj.Monoid;
import fj.data.Array;
import fj.data.List;
import fj.data.fingertrees.FingerTree;
import fj.data.fingertrees.MakeTree;

public class FunctionalJavaListTest {
	@Test
	public void testListPushBackGet() {
		List<Integer> a = List.list();
		for (int i = 0; i < 32; i++) {
			a = a.append(List.list(i)); // snoc
			for (int j = 0; j <= i; j++) {
				Assertions.assertEquals(j, a.index(j));
			}
		}
		a = List.list();
		for (int i = 0; i < 1000000; i++)
			a = a.append(List.list(i)); // snoc

		int i = 0;
		for (Integer e : a) {
			Assertions.assertEquals(i, e);
			i++;
		}
	}

	@Test
	public void testArrayPushBackGet() {
		Array<Integer> a = Array.empty();
		for (int i = 0; i < 32; i++) {
			a = a.append(Array.array(i));
			for (int j = 0; j <= i; j++) {
				Assertions.assertEquals(j, a.get(j));
			}
		}
		a = Array.empty();
		for (int i = 0; i < 1000000; i++)
			a = a.append(Array.array(i));

		int i = 0;
		for (Integer e : a) {
			Assertions.assertEquals(i, e);
			i++;
		}
	}
}
```

Because I read the paper and implement partial API for Java Collection, and it could take almost O(1) or O(log n) time for single element append. (See implementation https://github.com/morris821028/immortal-jellyfish)

I found we could use finger tree instead of these and take better performance. Therefore, why not wrap finger tree as List/Array?

```java
	@Test
	public void testFingerPushBackGet() {
		FingerTree<Integer, Integer> a = FingerTree.emptyIntAddition();
		for (int i = 0; i < 32; i++) {
			FingerTree<Integer, Integer> ft = FingerTree.emptyIntAddition();
			List.range(1, 1).foldLeft(ft2 -> t -> ft2.snoc(t), ft);
			a = a.append(ft);
			
			int j = 0;
			for (Integer e : iteratorToIterable(a.toStream().iterator())) {
				Assertions.assertEquals(j, e);
				j++;
			}
		}

		a = FingerTree.emptyIntAddition();
		for (int i = 0; i < 1000000; i++) {
			FingerTree<Integer, Integer> ft = FingerTree.emptyIntAddition();
			List.range(i, 1).foldLeft(ft2 -> t -> ft2.snoc(t), ft);
			a = a.append(ft);

		}

		int j = 0;
		for (Integer e : iteratorToIterable(a.toStream().iterator())) {
			Assertions.assertEquals(j, e);
			j++;
		}
	}
```

**Comment by tonymorris** [comment]
`snoc` is O(n) for a single-linked list.

**Comment by morris821028** [comment]
@tonymorris Could it be O(log n) for a doubly-linked list? The common interface of List is often implemented by doubly-linked list for better performance.

**Comment by tonymorris** [comment]
A double-linked list has O(1) `snoc` but does not give better performance. It gives a trade-off. You can obtain O(1) `cons` and `snoc` with:

```
// see fj.data.DList
public class DList<A> {
    private final F<List<A>,List<A>> appendFn;
}
```

Note that `head` and `tail` are O(n). A finger-tree gives different trades again.

**Comment by morris821028** [comment]
@tonymorris Thanks your information. I forgot to study DList in this project.

In `java.util`, `LinkedList` implements `Deque` interface. If we consider real-time deque as `DList` implementation corresponding to paper ***REAL-TIME DEQUES, MULTIHEAD TURING MACHINES and PURELY FUNCTIONAL PROGRAMMING, Tyng-Runey Chuang and Benjamin Goldberg, 1993***.

* `cons` and `snoc`: O(1)
* `head` and `tail`: O(1)
* `append(List)`: O(m), which m is the number of appended elements.

I'm interested in the real cases prefer which kind of operation?

**Comment by tonymorris** [comment]
I think both are useful. Feel free to write `Deque` as a pair of lists.

**Comment by mperry** [comment]
Closing.
