### ISSUE TITLE
build

### ISSUE THREAD

**Issue by tonymorris** [functionaljava/functionaljava#429]
Hey guys, what's the go with the build?

On Linux:

    % ./gradlew
    invalid flag: --release

On MacOS:

    % ./gradlew
    Cannot perform signing task ':core:signArchives' because it has no configured signatory

**Comment by mperry** [comment]
I'm pretty sure this is my fault @tonymorris.  I'll have a look this weekend, I'm just setting up an AWS instance, but pretty sure I know the issue.  I suspect the issue with --release is JDK 8 vs 11.  The sign archives is from the 4.9 release hangover and subsequent merge to 5.x.  I'll confirm both though.

**Comment by tonymorris** [comment]
An no worries, thanks mate.

**Comment by tonymorris** [comment]
Hey mate, anything I can do to help?

**Comment by mperry** [comment]
Hi @tonymorris, sorry, got busy.  Use JDK 11 and fixed signing archives to be off by default.  Can you try again?  Waiting for the cloud build to check, but that is using JDK 17, so I think there is an issue there.  

I think the FJ versions should target the main JVM versions that support particular bytecode instructions, so FJ 5 should target JVM 8, FJ 6 -> JVM 11, FJ 7 -> JVM 17.

**Comment by mperry** [comment]
Build using JDK 11 is passing, see https://travis-ci.org/github/functionaljava/functionaljava/builds/765463953.

**Comment by tonymorris** [comment]
Ta mate, will try in the next few days.
