### ISSUE TITLE
Generated pom dependencies inconsistent with gradle build

### ISSUE THREAD

**Issue by WilliamCollishaw** [functionaljava/functionaljava#437]
The test dependencies in the pom.xml are not consistent with versions defined in build.gradle files.

[This Github repo search](https://github.com/functionaljava/functionaljava/search?q=h2database) shows a version for `com.h2database:h2` is only defined in one place, as version `2.1.210`. However [the generated pom file](https://repo1.maven.org/maven2/org/functionaljava/functionaljava/5.0/functionaljava-5.0.pom) depends on version `1.4.199` which has a handful of vulnerabilities. 

The same applies for [junit and junit-vintage-engine](https://github.com/functionaljava/functionaljava/blob/series/5.x/build.gradle#L78)

**Comment by gliptak** [comment]
thank you for the highlights @WilliamCollishaw 

h2 version was updated with https://github.com/functionaljava/functionaljava/commit/df6e6f8ea2fee836794c365f93fc8839388fd02b and it happened after the `5.0` tag/release

**Comment by WilliamCollishaw** [comment]
@gliptak you are correct 😅. I appreciated you pointing that out.

https://github.com/functionaljava/functionaljava/blob/v5.0/core/build.gradle
