### ISSUE TITLE
Implement Predicate<T> 

### ISSUE THREAD

**Issue by amarpotghan** [functionaljava/functionaljava#98]
many times I ended up in writing following combinators, I think it would add some value if library has it :

1. F&lt;A, Bool&gt; and(F&lt;A, Bool&gt; pred1, F&lt;A, Bool&gt; pred2)
2. F&lt;A, Bool&gt; or(F&lt;A, Bool&gt; pred1, F&lt;A, Bool&gt; pred2)
3. F &lt; B, Bool &gt; comap(F&lt;B, A&gt;, F&lt;A, Bool&gt;)
4. F&lt;B, Bool&gt; notFor(F&lt;B, A&gt;, F&lt;A, Bool&gt;) [a la Haskell's Data.Function.Predicate's `isn't`]
4. F&lt;A, Bool&gt; inverse(F&lt;A, Bool&gt;)

additionally we could add:
nand, nor, xor
We can also implement Predicate2<A, B>, Predicate3<A, B, C> and so on.
thoughts?

**Comment by mperry** [comment]
I think we need these, the closest thing I can see is in the Booleans class (e.g. `Booleans.not`), so perhaps that is the best place to add these.

Personally, I don't think we need a Predicate class and related arities.  Given Java uses nominative typing I think conversion is a pain and would have few advantages.

I would encourage you to do this and submit a pull request.

**Comment by amarpotghan** [comment]
Now as I see through `Booleans`, definitely we don't need Predicates.

**Comment by techtangents** [comment]
I would also advise against a Predicate type. We had one in our fj 
equivalent, and removed it. It was just a hassle, and no benefit over 
simply writing F<A, Boolean>.

The 'and', 'or' etc functions for F<A, Boolean> are reasonable, though.

F<A, Boolean> forms 2 Moniods, one over 'and', one over 'or'. The 'or' 
variant is also an Alternative.

F<A, Boolean> or(List<F<A, Boolean>> fs) {...}
F<A, Boolean> and(List<F<A, Boolean>> fs) {...}

**Comment by amarpotghan** [comment]
@techtangents every function F<A, B> should form a monoid if B is monoid. Is my understanding correct?

**Comment by techtangents** [comment]
Sounds right to me.

**Comment by mperry** [comment]
This is addressed in PR #102.
